### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory, possible confliction with Iris Shaders?

### ISSUE THREAD

**Issue by Master65** [SrGnis/Creeper_AI_Updated#11]
This mod causes weird crashes for an unexplainable reason, returning this:

`java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.class_311.method_1596(class_311.java:18)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:29)
	at net.minecraft.class_630.method_22702(class_630.java:540)
	at net.minecraft.class_630.method_22699(class_630.java:133)
	at net.minecraft.class_4595.method_22961(class_4595.java:23)
	at net.minecraft.class_4595$$Lambda$9498/2093995989.accept(Unknown Source)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.minecraft.class_4595.method_2828(class_4595.java:23)
	at net.minecraft.class_4607.method_4199(class_4607.java:34)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)`

 I've checked the crash report and the only thing that pointed me towards this mod was:

`-- Entity being rendered --
Details:
	Entity Type: minecraft:creeper (net.minecraft.class_1548)
	Entity ID: 1252
	Entity Name: Creeper
	Entity's Exact location: 43.61, 73.00, -8.69
	Entity's Block location: World: (43,73,-9), Chunk: (at 11,4,7 in 2,-1; contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.04, -0.07, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null`

with the last line "`Entity's Vehicle: ~~ERROR~~ NullPointerException: null`" being the supposed culprit. 

I think this may be caused by Iris Shaders (this comes with a modified Sodium), but I cannot fully confirm this (decent chance this is the issue). The only known way to replicate this is to simply run shaders through Iris Shaders on Fabric 0.11.6 in Minecraft 1.16.5 and run around while spawning mobs (you need creepers to spawn in order for this to occur). I've gotten this crash to occur only in the overworld, both in day time and night time on hard difficulty.

Giving more detail on when and how the crash is occurring: it is not just an immediate crash. The game will first drop its FPS by half, or start as a sudden small lag spike. It will quickly escalate and get progressively worse about every 2-3 seconds, eventually causing a crash by a barrage of hard lag spikes at around 15-30 seconds of this starting. The rendering engine appears to completely crash right before the entire game crashes, which is where I think this could be incompatible with Iris Shaders.

Note: The crash reports always have the NullPointerException: null on a creeper every time; they're all identical.

**Comment by SrGnis** [comment]
Thanks for communicating the issue.

It seems that is a problem of Iris on the render of charged creepers and whiters as is explained in this [issue](https://github.com/IrisShaders/Iris/issues/689)
